import os
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, ListFlowable, ListItem
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER

def create_pdf(filename):
    doc = SimpleDocTemplate(filename, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    
    # Custom Styles (Times New Roman)
    styles.add(ParagraphStyle(name='Justify', fontName='Times-Roman', fontSize=12, leading=16, alignment=TA_JUSTIFY))
    styles.add(ParagraphStyle(name='TitleStyle', fontName='Times-Bold', fontSize=18, leading=22, alignment=TA_CENTER, spaceAfter=20))
    styles.add(ParagraphStyle(name='Heading1_Times', fontName='Times-Bold', fontSize=14, leading=18, spaceBefore=12, spaceAfter=6))
    styles.add(ParagraphStyle(name='Heading2_Times', fontName='Times-Bold', fontSize=12, leading=16, spaceBefore=10, spaceAfter=4))
    styles.add(ParagraphStyle(name='BulletStyle', fontName='Times-Roman', fontSize=12, leading=16, leftIndent=20))
    
    Story = []
    
    def add_heading(text, style='Heading1_Times'):
        Story.append(Paragraph(text, styles[style]))
        
    def add_paragraph(text):
        Story.append(Paragraph(text, styles['Justify']))
        Story.append(Spacer(1, 12))
        
    def add_bullet(text):
        Story.append(Paragraph(f"• {text}", styles['BulletStyle']))
        Story.append(Spacer(1, 6))

    # --- 1. Project Title and Team Members ---
    Story.append(Paragraph("Multi-Vendor Procurement & Purchase Order Management System", styles['TitleStyle']))
    add_heading("1. Project Title and Team Members")
    add_paragraph("<b>Project Title:</b> Multi-Vendor Procurement & Purchase Order Management System")
    add_paragraph("<b>Team Number:</b> Team 3")
    add_paragraph("<b>Team Members:</b> Nisarg Shah, Smit Patel, Parva Shah, Swet Patel, Priya")
    
    Story.append(Spacer(1, 20))
    
    # --- 2. Project Overview and Objective ---
    add_heading("2. Project Overview and Objective")
    add_paragraph("<b>Description of the project:</b> This project is a comprehensive, full-stack enterprise procurement platform designed to simulate a real-world purchasing workflow. It digitally manages the entire lifecycle of how an organization purchases goods from external vendors, integrating role-based access control, real-time budget tracking, and extensive audit logging.")
    add_paragraph("<b>Overall goal of the database system:</b> The primary goal is to digitize and streamline the multi-step, multi-department procurement process. By replacing manual paperwork with a centralized relational database, the system ensures data integrity, enforces strict department budget constraints, maintains a consistent state machine for all purchase requests, and provides actionable KPI metrics for management.")
    
    Story.append(Spacer(1, 10))
    
    # --- 3. Database Design ---
    add_heading("3. Database Design")
    add_paragraph("<b>Business rules summary:</b> The system enforces several critical business rules. Managers can only approve requests if the department has sufficient remaining budget. Users are strictly segregated by roles (Employee, Manager, Procurement, Vendor, Finance), and actions are restricted accordingly. Every status change in the procurement lifecycle is immutably logged in a history table.")
    add_paragraph("<b>ERD and schema explanation:</b> The database follows a normalized relational design (Third Normal Form) consisting of 16 interconnected tables divided into six functional groups: Authentication, Procurement Workflow, Vendor Management, Order Fulfillment, Finance, and System Monitoring. Key tables include Users, Departments, Purchase_Requests, Purchase_Orders, and Invoices.")
    add_paragraph("<b>Key design decisions:</b> Data redundancy is minimized by strictly defining foreign key relationships. Roles, Departments, and Vendor Categories are separated into distinct tables. A dedicated PR_Status_History table is used to create a robust audit trail of state changes, rather than merely overwriting a status column.")

    Story.append(Spacer(1, 10))

    # --- 4. Data Dictionary Overview ---
    add_heading("4. Data Dictionary Overview")
    add_paragraph("<b>Description of tables and relationships:</b>")
    add_bullet("<b>Users & Roles:</b> Manages user authentication and permissions. Users belong to Departments and are assigned specific Roles.")
    add_bullet("<b>Departments:</b> Tracks budget allocations and current expenditure.")
    add_bullet("<b>Purchase_Requests & Approvals:</b> Stores item requests generated by employees and the subsequent approval/rejection decisions made by managers.")
    add_bullet("<b>Purchase_Orders & Goods_Receipt:</b> Tracks official orders sent to vendors and records when physical goods are delivered.")
    add_bullet("<b>Invoices & Payments:</b> Manages the financial settlement of completed orders.")
    add_paragraph("<b>Key attributes and constraints:</b> Primary keys utilize AUTOINCREMENT integers. Foreign keys enforce referential integrity across all entities (e.g., a Purchase Order cannot exist without a valid Vendor and Purchase Request). NOT NULL constraints ensure critical data fields are always populated. Dates and timestamps are systematically recorded in US/Central time for audit consistency.")

    Story.append(Spacer(1, 10))
    
    # --- 5. SQL Implementation ---
    add_heading("5. SQL Implementation")
    add_paragraph("<b>Overview of table creation scripts:</b> The database was implemented using SQLite3. DDL scripts define tables with appropriate data types (INTEGER, TEXT, REAL, BOOLEAN) and establish foreign key constraints to maintain strict relational integrity.")
    add_paragraph("<b>Description of query categories:</b>")
    add_bullet("<b>Basic:</b> Standard INSERT and SELECT queries to manage user sessions and display initial dashboard data.")
    add_bullet("<b>Intermediate:</b> Multi-table JOINs used to compile comprehensive views, such as linking Purchase Orders to their respective Vendors and original Purchase Requests.")
    add_bullet("<b>Advanced:</b> Complex transactional queries that cascade status updates backwards across the workflow (e.g., updating a Purchase Request to 'PAID' when a Finance user clears an Invoice) and aggregate functions (SUM, COUNT) used to dynamically calculate remaining department budgets and KPI metrics.")
    add_paragraph("<b>Explanation of selected queries:</b> A critical implemented query is the budget deduction during the manager approval phase. The system performs a SELECT to verify the current 'budget_used' against 'budget_allocated'. If sufficient funds exist, an UPDATE adjusts the department's budget, followed by an INSERT into the PR_Approvals and PR_Status_History tables, executed within a single logical transaction to prevent race conditions.")

    Story.append(PageBreak())

    # --- 6. Frontend Integration ---
    add_heading("6. Frontend Integration (Optional Extra Credit)")
    add_paragraph("<b>Frontend tool/framework:</b> The frontend is built using HTML5, Custom CSS3 (implementing a modern dark theme with glassmorphism), and Bootstrap 5.3 for responsive layouts. Data visualization is powered by Chart.js. The application uses the Python Flask framework with Jinja2 for server-side template rendering.")
    add_paragraph("<b>Database connection:</b> The Flask backend connects to the SQLite database using Python's built-in sqlite3 library. A custom `get_db_connection()` function establishes the connection and utilizes the `sqlite3.Row` row factory to return records as dictionary-like objects, which are then passed seamlessly into Jinja2 templates for dynamic HTML rendering.")
    add_paragraph("<b>Screenshots showing interaction:</b> Live data is retrieved from the database and displayed as interactive KPI cards and data tables on role-specific dashboards. (Note: Visual screenshots of the frontend interface are provided in the separate project presentation slides).")

    Story.append(Spacer(1, 10))
    
    # --- 7. Challenges and Solutions ---
    add_heading("7. Challenges and Solutions")
    add_paragraph("<b>Issues encountered:</b> One major challenge was maintaining data consistency across the multi-stage procurement state machine. Initially, updating a Purchase Order's status did not reflect on the Employee's original Purchase Request, leading to disjointed data views. Additionally, enforcing strict budget constraints required careful transactional handling.")
    add_paragraph("<b>How the team addressed them:</b> We implemented a cascading status update mechanism in the backend routing. When a Vendor marks an order as 'SHIPPED', or Finance marks an invoice as 'PAID', the backend automatically traces the foreign keys backward to update the original Purchase Request and logs the transition in the history table. Budget constraints were resolved by validating the exact department funds dynamically before executing any approval queries.")

    Story.append(Spacer(1, 10))
    
    # --- 8. Conclusion ---
    add_heading("8. Conclusion")
    add_paragraph("<b>Summary of the project:</b> The Multi-Vendor Procurement system successfully digitizes a complex corporate workflow into an intuitive, secure, and highly responsive web application. It effectively demonstrates the power of relational databases in enforcing business logic and maintaining data integrity across distributed roles.")
    add_paragraph("<b>Key learnings:</b> The team gained significant experience in database normalization, managing foreign key dependencies, and executing complex SQL queries within a web application environment. We also learned the importance of comprehensive audit logging and transactional consistency.")
    add_paragraph("<b>Possible future improvements:</b> Future enhancements could include migrating the backend database from SQLite to PostgreSQL for better scalability, implementing automated email notifications for pending approvals using SendGrid, and building an external API endpoint to allow vendor systems to interface directly with the database.")

    # Build the PDF
    doc.build(Story)
    print(f"Successfully generated {filename}")

if __name__ == "__main__":
    create_pdf("docs/Team3_Final_Project_Report.pdf")
